Added multiple new functions for Papillon
LiterateInk/Pawdirecte pull request #4
Opened 2024-09-07 17:41 UTC by camarm-dev

# Description

This PR integrate some new ED functionnalities:
- Attendance (punishments, absences)
- More to come

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Currently not tested. PR will be marked as ready when tested.

- [ ] Tested with EcoleDirecte account using `examples/student-attendance.ts`

**Test Configuration**:

Desktop (please complete the following information) :
- OS: Ubuntu
- Browser: -
- Version: -

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-09-07 22:34 UTC, Vexcited commented on src/core/base64.ts
There's already the `js-base64` dependency to do that, just do `import { decode, encode } from "js-base64";`

You can't use `buffer` (and the package also) because it won't be supported in all environnement and kinda limited in React Native.

2024-09-07 22:35 UTC, Vexcited commented on package.json
> +    "buffer": "^6.0.3",
Please, try to avoid using this package as `Buffer` should NOT be used.

If you really need something similar, try using `Uint8Array` instead.

2024-09-28 15:57 UTC, camarm-dev commented
_J'avais commenté la mauvaise PR désolé pour le ping_
@Vexcited tu peux commencer à review 😉 ! On va rajouter les devoirs encore, ça va arriver petit à petit ce soir ! Merci (et bon courage 😄)

2024-09-28 17:27 UTC, imyanice commented
déjà fait une v1 des devoirs, donc feel free de review le code pour l'instant.

pour info sur les devoirs ed renvoie un content-type "text/html" donc on ne peut pas utiliser le Response() normal, pas de meilleures idées pour l'instant...

2024-09-28 20:24 UTC, camarm-dev commented
On a fini notre travail ! On est prêt pour les reviews !

2024-09-28 21:32 UTC, Vexcited requested changes

2024-09-28 21:32 UTC, Vexcited commented on src/api/student/attendance.ts
> +};
```suggestion
type AttendanceResponse = Readonly<{
  punishments: Array<AttendanceItem>
  absences: Array<AttendanceItem>
}>;
```

2024-09-28 21:32 UTC, Vexcited commented on src/api/student/cantine.ts
> +};
```suggestion
type CantineResponse = Readonly<{
  reservation?: CantineReservations
  barcode?: CantineBarcode
}>;
```

2024-09-28 21:32 UTC, Vexcited commented on src/api/student/cantine.ts
> +  });
```suggestion
  const reservations = account.modules.find((m: any) => m.code === "RESERVATIONS");
  const barcode = account.modules.find((m: any) => m.code === "CANTINE_BARCODE");
```

2024-09-28 21:32 UTC, Vexcited commented on src/api/student/documents.ts
> +  archive: string = ""
```suggestion
  archive = ""
```

2024-09-28 21:32 UTC, Vexcited commented on src/api/student/documents.ts
> +import {PawdirecteDocument, SessionTokenRequired, type Session} from "~/models";
```suggestion
import { type PawdirecteDocument, SessionTokenRequired, type Session } from "~/models";
```

2024-09-28 21:32 UTC, Vexcited commented on src/api/student/documents.ts
> +  const allDocuments = [].concat(response.data.factures).concat(response.data.notes).concat(response.data.viescolaire).concat(response.data.administratifs).concat(response.data.inscriptions);
```suggestion
  const allDocuments = [
    ...response.data.factures,
    ...response.data.notes,
    ...response.data.viescolaire,
    ...response.data.administratifs,
    ...response.data.inscriptions
  ];
```

2024-09-28 21:32 UTC, Vexcited commented on src/api/student/files.ts
> +export const buildPawdirecteFileDownloadUrl = (type: FileKind, id: number | string, year: string = "") => {
```suggestion
export const buildPawdirecteFileDownloadUrl = (type: FileKind, id: number | string, year = "") => {
```

2024-09-28 21:32 UTC, Vexcited commented on src/api/student/files.ts
> +  year: string = ""
```suggestion
  year = ""
```

2024-09-28 21:32 UTC, Vexcited commented on src/api/student/files.ts
> +  return await request.sendRaw(session.fetcher);
```suggestion
  return request.sendRaw(session.fetcher);
```

2024-09-28 21:32 UTC, Vexcited commented on src/api/student/grades.ts
> +};
Des fois j'accepte, mais là, tout ça, ça doit être dans un modèle (`~/models`), c'est vraiment énorme ici...

2024-09-28 21:32 UTC, Vexcited commented on src/api/student/grades.ts
> +};
C'est un decoder ça ? (`~/decoders`)

2024-09-28 21:32 UTC, Vexcited commented on src/api/student/homeworks.ts
> +  const request = new Request(`/Eleves/${account.id}/cahierdetexte/${date}.awp?verbe=get&v=4.62.1`)
```suggestion
  const request = new Request(`/Eleves/${account.id}/cahierdetexte/${date}.awp?verbe=get`)
```

La version est déjà ajoutée en dessous avec `.addVersionURL()`

2024-09-28 21:32 UTC, Vexcited commented on src/api/student/messages.ts
> +    content: Buffer.from(response.data.content, "base64").toString(),
Utilisez `decode` de `js-base64` pour faire ces opérations, React Native et les navigateurs (et certains runtimes) ne supportent PAS `Buffer`

2024-09-28 21:32 UTC, Vexcited commented on src/api/student/workspace.ts
> +  return response.data?.map(decodeWorkspace);
Pourquoi pas faire `return response.data?.map(decodeWorkspace) ?? []` et avoir `Promise<Array<WorkspaceItem>>` en type de retour ?

Est-ce qu'il y a vraiment besoin de retourner un autre type (ici `undefined`) pour le cas où aucune donnée est retournée ?

2024-09-28 21:32 UTC, Vexcited commented on src/core/base64.ts
En plus vous avez ce fichier, pourquoi utiliser `Buffer.from(..., "base64")` dans les autres fichiers ? 😭

2024-09-28 21:32 UTC, Vexcited commented on src/api/student/timetable.ts
> +  return response.data.map(decodeTimetableItem).sort((item: TimetableItem, item2: TimetableItem) => new Date(item.startDate) > new Date(item2.startDate));
```suggestion
  return response.data.map(decodeTimetableItem).sort((item: TimetableItem, item2: TimetableItem) => new Date(item.startDate).getTime() > new Date(item2.startDate).getTime());
```

Faites des comparaisons sur des entiers, c'est un peu plus rapide que de comparer des objets

2024-09-28 21:32 UTC, Vexcited commented on src/core/request.ts
> +    return await fetcher(this as UnsafeRequest);
```suggestion
    return fetcher(this as UnsafeRequest);
```

2024-09-28 21:32 UTC, Vexcited commented on src/core/response.ts
> +      }
Cette vérification est-elle faite exprès ?

Vous vérifiez si `access_token` existe dans `content` puis vous utilisez `content.accessToken` après (donc pas la même propriété) ?

2024-09-28 21:32 UTC, Vexcited commented on src/decoders/document-kind.ts
C'est une façon assez spéciale de faire un `as DocumentKind`...

Si la valeur est exactement pareille à celle du modèle, vous pouvez faire `response.something as DocumentKind` dans le decoder, ça revient à la même chose.

2024-09-28 21:32 UTC, Vexcited commented on src/decoders/document.ts
> +export const decodeDocument = (item: any): PawdirecteDocument => {
Le nom du decoder doit correspondre avec celui du modèle, donc ici ça devrait être `decodePawdirecteDocument` mais ça fait pas de sens, il faudrait que le modèle s'appelle `Document` tout court.

2024-09-28 21:32 UTC, Vexcited commented on src/decoders/grade-value.ts
> +    case "Disp ":
Pourquoi pas faire `value = value.trim()` au début de la fonction pour éviter les doublons inutiles ?

2024-09-28 21:32 UTC, Vexcited commented on src/models/grade-kind.ts
> +// Stolen from pawnote
EcoleDirecte supporte vraiment tout ces types de notes ?

2024-09-28 21:36 UTC, camarm-dev commented on src/models/grade-kind.ts
> +// Stolen from pawnote
Ecoledirecte ne supporte aucun type de notes: il ne renvoie qu'une string, vide, avec une note, ou avec un label chelou tel que "Disp " ou "Abs "... Je vais corriger ça.

2024-09-28 21:37 UTC, camarm-dev commented on src/decoders/grade-value.ts
> +    case "Disp ":
**À vérifier**, mais il me semble que le code actuel en lui même est une erreur: "Disp" et "Disp " sont 2 statuts disctincts (je vais vérifier ça aussi).

2024-09-28 21:39 UTC, camarm-dev commented on src/decoders/document.ts
> +export const decodeDocument = (item: any): PawdirecteDocument => {
Document est le type qui corresspond à `window.document` en javascript... Nommer un type `Document` ça va créé des embrouilles de type pour le développement... Je peux le nommer `Document` si tu préfères après..

2024-09-28 21:41 UTC, camarm-dev commented on src/api/student/documents.ts
> +  archive: string = ""
Pourquoi enlever le type ? C'est toujours utile pour les IDE / pour typescript nan ?

2024-09-28 21:43 UTC, camarm-dev commented on src/api/student/files.ts
> +export const buildPawdirecteFileDownloadUrl = (type: FileKind, id: number | string, year: string = "") => {
| https://github.com/LiterateInk/Pawdirecte/pull/4#discussion_r1779790344

2024-09-28 21:43 UTC, Vexcited commented on src/api/student/documents.ts
> +  archive: string = ""
Quand tu donnes une valeur par défaut, ça infer automatiquement au type de cette valeur par défaut, pas vraiment utile ici (c'est pas non plus un *slow-type* donc aucune difficulté pour TS ou les IDE)

2024-09-28 21:45 UTC, camarm-dev commented on src/api/student/grades.ts
> +};
Je peux laisser le `GradesResponse` ?

2024-09-28 21:46 UTC, Vexcited commented on src/decoders/document.ts
> +export const decodeDocument = (item: any): PawdirecteDocument => {
Sauf que c'est un type TS et pas une classe JS ou autre !

On peut très bien l'exporter sans problème, si jamais y a un conflit dans une application web tu peux juste faire `import type { Document as PawdirecteDocument } from "pawdirecte"` dans le code de l'application et il n'y aura pas de conflits.

2024-09-28 21:46 UTC, camarm-dev commented on src/api/student/files.ts
> +  year: string = ""
| https://github.com/LiterateInk/Pawdirecte/pull/4#discussion_r1779790344

2024-09-28 21:47 UTC, Vexcited commented on src/api/student/files.ts
> +export const buildPawdirecteFileDownloadUrl = (type: FileKind, id: number | string, year: string = "") => {
Déjà répondu du coup

2024-09-28 21:47 UTC, Vexcited commented on src/api/student/files.ts
> +  year: string = ""
Déjà répondu du coup

2024-09-28 21:49 UTC, Vexcited commented on src/api/student/grades.ts
> +};
Oui tu peux, cependant je le changerai d'endroit sûrement plus tard pour être entièrement conforme à la structure imposée (c'est pas pour être chiant mais c'est juste que pour la ré-implémentation dans un autre langage c'est beaucoup plus facile...)

2024-09-28 22:05 UTC, camarm-dev commented on src/core/base64.ts
C'était pas moi 😭 (@imyanice je dénonce pas tqt)

2024-09-28 23:35 UTC, Vexcited approved these changes

2024-09-28 23:35 UTC, merged